### ISSUE TITLE
App Disables Bluetooth on exit

### ISSUE THREAD

**Issue by julian-labuschagne** [janpansa/arduino_bluetooth_android#2]
When you exit the application it disables Bluetooth this disconnects all the Bluetooth devices including for example my ShoxSPIN bluetooth speakers and my Smart Watch galaxy gear.

**Comment by janpansa** [comment]
I will disable this functionality, however, might look into this in the
future. Perhaps one can check if the bluetooth was ON when the application
is first opened and then only turn off bluetooth on exit if this was the
case. This can however cause other issues for instance when you pause the
app, open another bluedtooth app, then resume the app and exit.

But yes, I will disable this functiojnality for now. (Thursday.Friday)

On Mon, Jul 27, 2015 at 4:45 PM, Julian notifications@github.com wrote:

> When you exit the application it disables Bluetooth this disconnects all
> the Bluetooth devices including for example my ShoxSPIN bluetooth speakers
> and my Smart Watch galaxy gear.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/janpansa/arduino_bluetooth_android/issues/2.

## 

Gideon van der Merwe
Jnr. Database Administrator
University of Pretoria
Onderstepoort
0125298470

**Comment by julian-labuschagne** [comment]
I think a simple solution to this would be when you display the "Are you sure you want to exit" message dialog add a small check-box with a label "Turn off Bluetooth"

**Comment by janpansa** [comment]
Noted, think this is the best solution.

**Comment by janpansa** [comment]
I added the check on the exit dialog. Also, it will not show the checkbox on the alert dialog if the bluetooth is off. I also made sure that the check for turning bluetooth on or off is done after the user pressed the yes button (yes to exit), this means the checkbox only gets evasluated after the user has actually exited.
